Repository Hirochon/Shappar, pull requests merged in 2020-05, with the labels that each got.

#270 [mod] マイページでの不具合修正と制限を追加
  accounts/custom_views.py
  accounts/forms.py
  accounts/migrations/0001_initial.py
  apiv1/migrations/0001_initial.py
  apiv1/migrations/0002_auto_20200419_0446.py
  apiv1/serializers.py
  apiv1/tests/test_serializers.py
  apiv1/tests/test_views.py
  apiv1/views.py
  config/create.py
  templates/errors/403.html
Labels: modify, update

#273 [deploy] 本番環境にデプロイ
  .gitignore
  accounts/adapter.py
  accounts/admin.py
  accounts/custom_views.py
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/urls.py
  apiv1/migrations/0001_initial.py
  apiv1/models.py
  apiv1/serializers.py
  apiv1/tests/test_serializers.py
  apiv1/tests/test_views.py
  apiv1/views.py
  config/create.py
  config/settings/local.py
  config/urls.py
  config/views.py
  front/shappar-front/__mocks__/api.js
  front/shappar-front/__mocks__/localstorageMock.js
  front/shappar-front/__tests__/App.spec.js
  front/shappar-front/__tests__/components/DoughnutChart.spec.js
  front/shappar-front/__tests__/components/DrawerMemu.spec.js
  front/shappar-front/__tests__/components/GlobalMessage.spec.js
  front/shappar-front/__tests__/components/PostList.spec.js
  front/shappar-front/__tests__/components/Search.spec.js
  front/shappar-front/__tests__/components/UpdateUser.spec.js
  front/shappar-front/__tests__/views/LoginPage.spec.js
  front/shappar-front/__tests__/views/MyPage.spec.js
  front/shappar-front/__tests__/views/New.spec.js
  front/shappar-front/__tests__/views/PostDetails.spec.js
  front/shappar-front/__tests__/views/Public.spec.js
  front/shappar-front/package-lock.json
  front/shappar-front/package.json
  front/shappar-front/src/components/DrawerMenu.vue
  front/shappar-front/src/components/GlobalMessage.vue
  front/shappar-front/src/components/PostList.vue
  front/shappar-front/src/components/Search.vue
  front/shappar-front/src/services/api.js
  front/shappar-front/src/store/index.js
  front/shappar-front/src/views/Home.vue
  front/shappar-front/src/views/LoginPage.vue
  front/shappar-front/src/views/MyPage.vue
  front/shappar-front/src/views/New.vue
  front/shappar-front/src/views/PostDetails.vue
  front/shappar-front/src/views/UpdateUser.vue
  static/account/css/style.css
  templates/account/create_user.html
  templates/account/custom_email_confirmed.html
  templates/account/email_confirm.html
  templates/errors/403.html
  templates/home.html
Labels: deploy

#275 [mod] メールアドレス確認後にログイン画面へ遷移できるように変更
  config/urls.py
  templates/account/custom_email_confirmed.html
Labels: modify

#276 アイコンの変更とその他微修正
  front/shappar-front/.eslintrc.js
  front/shappar-front/public/favicon.ico
  front/shappar-front/public/img/icons/android-chrome-192x192.png
  front/shappar-front/public/img/icons/android-chrome-192x912.png
  front/shappar-front/public/img/icons/android-chrome-512x512.png
  front/shappar-front/public/img/icons/android-chrome-maskable-192x192.png
  front/shappar-front/public/img/icons/android-chrome-maskable-192x912.png
  front/shappar-front/public/img/icons/android-chrome-maskable-512x512 .png
  front/shappar-front/public/img/icons/android-chrome-maskable-512x512.png
  front/shappar-front/public/img/icons/apple-touch-icon-120x120.png
  front/shappar-front/public/img/icons/apple-touch-icon-152x152.png
  front/shappar-front/public/img/icons/apple-touch-icon-180x180.png
  front/shappar-front/public/img/icons/apple-touch-icon-60x60.png
  front/shappar-front/public/img/icons/apple-touch-icon-76x76.png
  front/shappar-front/public/img/icons/apple-touch-icon.png
  front/shappar-front/public/img/icons/favicon-16x16.png
  front/shappar-front/public/img/icons/favicon-32x32.png
  front/shappar-front/public/img/icons/msapplication-icon-144x144.png
  front/shappar-front/public/img/icons/mstile-150x150.png
  front/shappar-front/public/img/icons/safari-pinned-tab.svg
  front/shappar-front/src/assets/logo-min (コピー).png
  front/shappar-front/src/assets/logo-min.png
  front/shappar-front/src/assets/logo.png
  front/shappar-front/src/views/LoginPage.vue
  front/shappar-front/src/views/Public.vue
  static/account/css/style.css
  static/css/app.06907c02.css
  static/css/app.279b4975.css
  static/favicon.ico
  static/img/icons/android-chrome-192x192.png
  static/img/icons/android-chrome-192x912.png
  static/img/icons/android-chrome-maskable-192x192.png
  static/img/icons/android-chrome-maskable-192x912.png
  static/img/icons/android-chrome-maskable-512x512 .png
  static/img/icons/android-chrome-maskable-512x512.png
  static/img/icons/apple-touch-icon-120x120.png
  static/img/icons/apple-touch-icon-152x152.png
  static/img/icons/apple-touch-icon-180x180.png
  static/img/icons/apple-touch-icon-60x60.png
  static/img/icons/apple-touch-icon-76x76.png
  static/img/icons/apple-touch-icon.png
  static/img/icons/favicon-16x16.png
  static/img/icons/favicon-32x32.png
  static/img/icons/msapplication-icon-144x144.png
  static/img/icons/mstile-150x150.png
  static/img/icons/safari-pinned-tab.svg
  static/js/app.368a32a9.js
  static/js/app.53e78066.js
  static/js/chunk-vendors.803e2619.js
  static/js/chunk-vendors.cae7f54f.js
  static/precache-manifest.5fc39512d6e2a29075142cad431f9a68.js
  static/service-worker.js
  templates/index.html
Labels: modify

#277 [mod] adminページのURLを環境変数に変更
  config/settings/circleci.py
  config/settings/local.py
  config/settings/product.py
  config/urls.py
Labels: modify

#278 [deploy] 本番環境へデプロイ
  config/settings/circleci.py
  config/settings/local.py
  config/settings/product.py
  config/urls.py
  front/shappar-front/.eslintrc.js
  front/shappar-front/public/favicon.ico
  front/shappar-front/public/img/icons/android-chrome-192x192.png
  front/shappar-front/public/img/icons/android-chrome-192x912.png
  front/shappar-front/public/img/icons/android-chrome-512x512.png
  front/shappar-front/public/img/icons/android-chrome-maskable-192x192.png
  front/shappar-front/public/img/icons/android-chrome-maskable-192x912.png
  front/shappar-front/public/img/icons/android-chrome-maskable-512x512 .png
  front/shappar-front/public/img/icons/android-chrome-maskable-512x512.png
  front/shappar-front/public/img/icons/apple-touch-icon-120x120.png
  front/shappar-front/public/img/icons/apple-touch-icon-152x152.png
  front/shappar-front/public/img/icons/apple-touch-icon-180x180.png
  front/shappar-front/public/img/icons/apple-touch-icon-60x60.png
  front/shappar-front/public/img/icons/apple-touch-icon-76x76.png
  front/shappar-front/public/img/icons/apple-touch-icon.png
  front/shappar-front/public/img/icons/favicon-16x16.png
  front/shappar-front/public/img/icons/favicon-32x32.png
  front/shappar-front/public/img/icons/msapplication-icon-144x144.png
  front/shappar-front/public/img/icons/mstile-150x150.png
  front/shappar-front/public/img/icons/safari-pinned-tab.svg
  front/shappar-front/src/assets/logo-min (コピー).png
  front/shappar-front/src/assets/logo-min.png
  front/shappar-front/src/assets/logo.png
  front/shappar-front/src/views/LoginPage.vue
  front/shappar-front/src/views/Public.vue
  static/account/css/style.css
  static/css/app.06907c02.css
  static/css/app.279b4975.css
  static/favicon.ico
  static/img/icons/android-chrome-192x192.png
  static/img/icons/android-chrome-192x912.png
  static/img/icons/android-chrome-maskable-192x192.png
  static/img/icons/android-chrome-maskable-192x912.png
  static/img/icons/android-chrome-maskable-512x512 .png
  static/img/icons/android-chrome-maskable-512x512.png
  static/img/icons/apple-touch-icon-120x120.png
  static/img/icons/apple-touch-icon-152x152.png
  static/img/icons/apple-touch-icon-180x180.png
  static/img/icons/apple-touch-icon-60x60.png
  static/img/icons/apple-touch-icon-76x76.png
  static/img/icons/apple-touch-icon.png
  static/img/icons/favicon-16x16.png
  static/img/icons/favicon-32x32.png
  static/img/icons/msapplication-icon-144x144.png
  static/img/icons/mstile-150x150.png
  static/img/icons/safari-pinned-tab.svg
  static/js/app.368a32a9.js
  static/js/app.53e78066.js
  static/js/chunk-vendors.803e2619.js
  static/js/chunk-vendors.cae7f54f.js
  static/precache-manifest.5fc39512d6e2a29075142cad431f9a68.js
  static/service-worker.js
  templates/account/custom_email_confirmed.html
  templates/index.html
Labels: deploy

#281 [mod] ユーザー作成ページのCSSを追加&メールアドレス確認文章を変更
  front/shappar-front/public/account/css/style.css
  static/account/css/style.css
  templates/account/custom_email_confirmed.html
  templates/home.html
Labels: modify

#285 [mod]Readmeの内容を変更
  README.md
Labels: modify, update

#287 [add] メールアドレス確認後とメタタグに関してHTMLを追加
  config/settings/circleci.py
  config/settings/local.py
  config/settings/product.py
  front/shappar-front/public/index.html
  templates/account/custom_email_confirmed.html
Labels: update

#299 [mod] メールアドレス確認時のエラーを修正
  accounts/custom_views.py
  templates/account/custom_email_confirmed.html
  templates/account/email_confirm.html
Labels: modify

#300 [deploy] デプロイします
  accounts/custom_views.py
  templates/account/custom_email_confirmed.html
  templates/account/email_confirm.html
Labels: deploy
