Repository Hirochon/Shappar, pull requests merged in 2020-03, with the labels that each got.

#42 [add] docker-compose up時にmigrate関連も同時に行える機能を追加
  .gitignore
  apiv1/migrations/0003_auto_20200228_2349.py
  apiv1/migrations/0004_auto_20200229_0028.py
  config/wsgi.py
  docker-compose.yml
  nginx/conf/nginx.conf
Labels: enhancement

#51 [add] 機能を追加&修正しました！
  apiv1/urls.py
  apiv1/views.py
Labels: modify, update

#53 [add] 選択したデータを保持できるように機能を追加
  apiv1/migrations/0001_initial.py
  apiv1/migrations/0002_auto_20200220_1727.py
  apiv1/migrations/0003_auto_20200228_2349.py
  apiv1/migrations/0004_auto_20200229_0028.py
  apiv1/migrations/0005_auto_20200306_2316.py
  apiv1/models.py
  apiv1/serializers.py
  apiv1/views.py
Labels: update

#54 [mod] typo
  apiv1/views.py
Labels: bug

#58 [mod] 選択済みの選択肢出力時のバグを修正&管理者画面修正
  apiv1/admin.py
  apiv1/views.py
Labels: bug, update

#86 現在使用しているAPIの差分を修正
  Swagger/swagger_api_v1.yml
Labels: modify

#87 [add]各種修正・バリデーション機能・下書き保存機能
  front/shappar-front/src/App.vue
  front/shappar-front/src/components/GlobalMessage.vue
  front/shappar-front/src/components/PostList.vue
  front/shappar-front/src/components/Search.vue
  front/shappar-front/src/views/MyPage.vue
  front/shappar-front/src/views/New.vue
  front/shappar-front/src/views/Public.vue
Labels: update

#91 [mod]#90_マイページの過去の投票・投稿取得APIを修正
  Swagger/swagger_api_v1.yml
Labels: modify

#92 [mod]#88,89_ユーザー情報更新ページの変更・微修正
  front/shappar-front/src/components/GlobalMessage.vue
  front/shappar-front/src/components/PostList.vue
  front/shappar-front/src/components/Search.vue
  front/shappar-front/src/main.js
  front/shappar-front/src/views/Admin.vue
  front/shappar-front/src/views/LoginPage.vue
  front/shappar-front/src/views/MyPage.vue
  front/shappar-front/src/views/New.vue
  front/shappar-front/src/views/Public.vue
  front/shappar-front/src/views/UpdateUser.vue
Labels: modify

#93 [add] マイページに投稿済み一覧&投票済み一覧の表示機能を追加
  apiv1/urls.py
  apiv1/views.py
Labels: enhancement

#101 [mod]#94_マイページの過去の投票・投稿表示機能の修正・デザイン修正
  front/shappar-front/src/components/Search.vue
  front/shappar-front/src/main.js
  front/shappar-front/src/views/MyPage.vue
  front/shappar-front/src/views/UpdateUser.vue
  static/css/app.4465741c.css
  static/css/app.45da9327.css
  static/css/chunk-vendors.fbe9bade.css
  static/js/app.b804dc68.js
  static/js/app.c6904265.js
  static/js/chunk-vendors.07afd726.js
  static/js/chunk-vendors.a7e7d16a.js
  templates/index.html
Labels: modify

#102 [fix]#95_ユーザー情報更新時の問題修正
  front/shappar-front/src/components/DrawerMenu.vue
  front/shappar-front/src/components/Search.vue
  front/shappar-front/src/main.js
  front/shappar-front/src/services/api.js
  front/shappar-front/src/views/MyPage.vue
  front/shappar-front/src/views/New.vue
  front/shappar-front/src/views/Public.vue
  front/shappar-front/src/views/UpdateUser.vue
Labels: bug, modify, update

#107 [add] 投稿詳細&投稿削除機能を追加しました！
  apiv1/serializers.py
  apiv1/urls.py
  apiv1/views.py
  config/settings/local.py
  templates/account/email/email_confirmation_message.txt
Labels: update

#111 [mod] 投稿詳細機能のKeyを変更
  apiv1/views.py
Labels: modify

#112 [mod]#106,109_投稿削除API・投稿詳細取得APIの設計
  Swagger/swagger_api_v1.yml
Labels: modify

#115 [mod]#97,98_FontAwesomeIconの配置の仕方を変更・ユーザー情報更新送信前バリデーション追加
  front/shappar-front/src/components/PostList.vue
  front/shappar-front/src/components/Search.vue
  front/shappar-front/src/views/MyPage.vue
  front/shappar-front/src/views/New.vue
  front/shappar-front/src/views/Public.vue
  front/shappar-front/src/views/UpdateUser.vue
  static/css/app.4465741c.css
  static/css/app.cbc3ecb1.css
  static/css/chunk-vendors.1487d421.css
  static/js/app.ba0aed38.js
  static/js/app.c6904265.js
  static/js/chunk-vendors.3ff23ac2.js
  templates/index.html
Labels: modify, update

#118 [fix]#117_acornパッケージの脆弱性他数件修正
  front/shappar-front/package-lock.json
  front/shappar-front/package.json
  static/js/app.8063d313.js
  templates/index.html
Labels: bug

#132 CircleCIによる自動デプロイを実装しました！！
  .circleci/config.yml
  .gitignore
  config/settings/product.py
Labels: enhancement

#134 [fix]#133_manifest.jsonのstart-urlを変更
  front/shappar-front/public/manifest.json
  static/js/app.4fb92348.js
  static/manifest.json
  static/precache-manifest.4268e23b2818746410fce0963220f843.js
  static/service-worker.js
  templates/index.html
Labels: bug

#137 [mod] 最低限の認証機能を実装しました！
  apiv1/views.py
  config/settings/product.py
  config/urls.py
Labels: bug, enhancement

#138 [deploy]本番環境へデプロイ
  apiv1/views.py
  config/settings/product.py
  config/urls.py
  front/shappar-front/public/manifest.json
  static/js/app.4fb92348.js
  static/manifest.json
  static/precache-manifest.4268e23b2818746410fce0963220f843.js
  static/service-worker.js
  templates/index.html
Labels: deploy

#142 [add] バリデーションを追加したことによるバグの修正＆エラーレスポンスを定義
  Makefile
  apiv1/serializers.py
  apiv1/urls.py
  apiv1/views.py
  config/settings/product.py
Labels: documentation, enhancement, modify

#146 [add]#113,116,121_投稿詳細機能の実装その他
  Swagger/swagger_api_v1.yml
  front/shappar-front/package-lock.json
  front/shappar-front/package.json
  front/shappar-front/public/manifest.json
  front/shappar-front/src/components/DoughnutChart.vue
  front/shappar-front/src/components/GlobalMessage.vue
  front/shappar-front/src/components/PostList.vue
  front/shappar-front/src/components/Search.vue
  front/shappar-front/src/main.js
  front/shappar-front/src/router/index.js
  front/shappar-front/src/services/api.js
  front/shappar-front/src/store/index.js
  front/shappar-front/src/views/PostDetails.vue
  front/shappar-front/src/views/Public.vue
Labels: modify, update

#148 [add] 投稿時のテスト機能を追加！
  .circleci/config.yml
  Makefile
  apiv1/tests.py
  apiv1/tests/__init__.py
  apiv1/tests/test_views.py
  apiv1/views.py
  config/settings/circleci.py
  config/settings/local.py
Labels: update

#151 [add] マイページのテスト機能を追加&CircleCIの環境変数設定を変更！
  apiv1/tests/test_views.py
  apiv1/views.py
  config/settings/circleci.py
  config/settings/product.py
Labels: enhancement, update

#154 [add] 投票機能に関するテストを追加&テスト用の設定ファイルを変更しました！！
  apiv1/tests/test_views.py
  apiv1/views.py
  config/settings/circleci.py
  config/settings/local.py
Labels: modify, update

#156 [add] 投稿の削除＆投票情報更新＆投票済み一覧表示のテストを追加！
  apiv1/tests/test_views.py
  apiv1/views.py
Labels: update

#162 [add] OptionSerializerのテスト/Makefileの設定を追加
  Makefile
  apiv1/serializers.py
  apiv1/tests/test_serializers.py
  apiv1/views.py
Labels: invalid, modify, update

#163 [mod]#145_微修正多数
  front/shappar-front/src/assets/common.scss
  front/shappar-front/src/components/DrawerMenu.vue
  front/shappar-front/src/components/GlobalMessage.vue
  front/shappar-front/src/components/PostList.vue
  front/shappar-front/src/components/Search.vue
  front/shappar-front/src/main.js
  front/shappar-front/src/router/index.js
  front/shappar-front/src/views/LoginPage.vue
  front/shappar-front/src/views/MyPage.vue
  front/shappar-front/src/views/New.vue
  front/shappar-front/src/views/PostDetails.vue
  front/shappar-front/src/views/Public.vue
  front/shappar-front/src/views/UpdateUser.vue
Labels: modify

#166 [mod] Django設定ファイル環境変数の定義を修正
  config/settings/product.py
Labels: bug, modify

#167 [deploy]本番環境へデプロイ
  config/settings/product.py
Labels: deploy

#172 [add] マイページにて他人の投稿の投票結果が表示されないように条件を追加
  apiv1/views.py
Labels: bug, modify

#173 [deploy]本番環境へデプロイ
  apiv1/views.py
Labels: deploy

#175 [mod] 投票詳細のレスポンスを修正
  apiv1/views.py
Labels: modify

#176 [deploy]本番環境へデプロイ
  apiv1/views.py
Labels: deploy

#178 [mod]画面リサイズ時の表示を修正
  front/shappar-front/src/components/NavBar.vue
  front/shappar-front/src/components/Post.vue
  front/shappar-front/src/components/PostList.vue
  front/shappar-front/src/main.js
  front/shappar-front/src/views/Home.vue
  front/shappar-front/src/views/MyPage.vue
  front/shappar-front/src/views/New.vue
  front/shappar-front/src/views/PostDetails.vue
  front/shappar-front/src/views/UpdateUser.vue
  static/css/app.470e8cdc.css
  static/css/app.b637163f.css
  static/js/app.6b9b81ea.js
  static/js/app.89962711.js
  static/js/chunk-vendors.0ee9a6e7.js
  static/precache-manifest.bf1ed3f7539a72880ab754502c306a27.js
  static/service-worker.js
  templates/index.html
Labels: bug, modify

#179 [deploy]本番環境へデプロイします
  front/shappar-front/src/components/NavBar.vue
  front/shappar-front/src/components/Post.vue
  front/shappar-front/src/components/PostList.vue
  front/shappar-front/src/main.js
  front/shappar-front/src/views/Home.vue
  front/shappar-front/src/views/MyPage.vue
  front/shappar-front/src/views/New.vue
  front/shappar-front/src/views/PostDetails.vue
  front/shappar-front/src/views/UpdateUser.vue
  static/css/app.470e8cdc.css
  static/css/app.b637163f.css
  static/js/app.6b9b81ea.js
  static/js/app.89962711.js
  static/js/chunk-vendors.0ee9a6e7.js
  static/precache-manifest.bf1ed3f7539a72880ab754502c306a27.js
  static/service-worker.js
  templates/index.html
Labels: deploy

#181 [deploy]本番環境にデプロイします
  config/settings/local.py
Labels: deploy

#185 [add] リダイレクト設定&静的ファイル配信機能の追加
  config/settings/local.py
  config/urls.py
  docker-compose.yml
Labels: enhancement

#191 [add] READMEにShapparをもっと知っていただけるような紹介を追加
  README.md
Labels: dependencies, update

#188 [add] CircleCIによる静的ファイルのS3へ自動デプロイ機能の追加
  .circleci/config.yml
Labels: update

#199 [mod]デザイン崩れなど修正
  accounts/forms.py
  front/shappar-front/bash
  front/shappar-front/gulp/gulpfile.js
  front/shappar-front/gulp/package-lock.json
  front/shappar-front/gulp/package.json
  front/shappar-front/gulp/style.scss
  front/shappar-front/public/css/style.min.css
  front/shappar-front/public/manifest.json
  front/shappar-front/src/components/DrawerMenu.vue
  front/shappar-front/src/components/PostList.vue
  front/shappar-front/src/components/Search.vue
  front/shappar-front/src/router/index.js
  front/shappar-front/src/services/api.js
  front/shappar-front/src/store/index.js
  front/shappar-front/src/views/Home.vue
  front/shappar-front/src/views/LoginPage.vue
  front/shappar-front/src/views/MyPage.vue
  front/shappar-front/src/views/PostDetails.vue
  front/shappar-front/src/views/Public.vue
  front/shappar-front/src/views/UpdateUser.vue
  static/css/app.470e8cdc.css
  static/css/app.c6308595.css
  static/css/style.min.css
  static/js/app.89962711.js
  static/js/app.a8c8431d.js
  static/manifest.json
  static/precache-manifest.468b057b4d04914097d0022618b182a4.js
  static/service-worker.js
  templates/account/email_confirm.html
  templates/account/signup.html
  templates/base.html
  templates/home.html
  templates/index.html
Labels: modify

#201 [mod] メール確認後のリダイレクト先を変更
  accounts/custom_views.py
  accounts/urls.py
  accounts/views.py
  templates/account/email_confirm.html
Labels: modify

#204 [add] フィールドに新たな要素を追加＆リファクタリング
  .circleci/config.yml
  Makefile
  accounts/adapter.py
  accounts/admin.py
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_auto_20200331_2237.py
  accounts/models.py
  apiv1/admin.py
  apiv1/migrations/0001_initial.py
  apiv1/models.py
  apiv1/serializers.py
  apiv1/tests/test_views.py
  apiv1/views.py
Labels: update

#205 [mod]#139_swaggerのAPI詳細変更
  Swagger/swagger_api_v1.yml
Labels: modify

#207 [mod] バックエンド側に静的解析ツールを導入
  accounts/custom_views.py
  accounts/forms.py
  accounts/models.py
  accounts/tests.py
  accounts/urls.py
  apiv1/admin.py
  apiv1/serializers.py
  apiv1/tests/test_serializers.py
  apiv1/tests/test_views.py
  apiv1/urls.py
  apiv1/views.py
  config/settings/circleci.py
  config/settings/local.py
  config/settings/product.py
  config/storage_backends.py
  config/urls.py
  config/wsgi_circleci.py
Labels: enhancement

#209 [add]#208_ランキング機能の追加
  Swagger/swagger_api_v1.yml
Labels: update

#212 [add] ランキング機能に順位を追加
  apiv1/views.py
Labels: update

#213 [add]血液型への対応、ランキングの活用
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_auto_20200331_2237.py
  apiv1/migrations/0001_initial.py
  front/shappar-front/.gitignore
  front/shappar-front/config/storybook/main.js
  front/shappar-front/package-lock.json
  front/shappar-front/package.json
  front/shappar-front/src/assets/common.scss
  front/shappar-front/src/components/DrawerMenu.vue
  front/shappar-front/src/components/MyButton.vue
  front/shappar-front/src/components/PostList.vue
  front/shappar-front/src/components/Search.vue
  front/shappar-front/src/main.js
  front/shappar-front/src/store/index.js
  front/shappar-front/src/stories/index.stories.js
  front/shappar-front/src/stories/index.stories.mdx
  front/shappar-front/src/views/New.vue
  front/shappar-front/src/views/PostDetails.vue
  front/shappar-front/src/views/Public.vue
  front/shappar-front/src/views/UpdateUser.vue
  static/css/app.6ffca573.css
  static/css/app.ad37c08c.css
  static/js/app.83cfdc30.js
  static/js/app.fc944e2b.js
  static/js/chunk-vendors.803e2619.js
  static/precache-manifest.fa5baddb5d1c12c327873772cf15fb50.js
  static/service-worker.js
  templates/index.html
Labels: update

#215 [add] マイページユーザーの投稿一覧表示機能のテストを追加(正常)
  apiv1/tests/test_views.py
  apiv1/views.py
Labels: modify, update
