Repository Hirochon/Shappar, pull requests merged in 2020-04, with the labels that each got.

#218 [deploy]本番環境へデプロイ
  README.md
Labels: deploy

#219 [mod] circleciのconfigファイルを変更
  .circleci/config.yml
Labels: modify

#220 [deploy]本番環境へデプロイ
  .circleci/config.yml
Labels: deploy, modify

#226 [mod] テストのリファクタリングと投票数ランキングのテスト追加
  apiv1/models.py
  apiv1/tests/test_views.py
  requirements.txt
Labels: modify, refactoring, update

#234 [mod]気づいた修正点を多数修正
  front/shappar-front/package-lock.json
  front/shappar-front/public/index.html
  front/shappar-front/src/assets/common.scss
  front/shappar-front/src/components/DrawerMenu.vue
  front/shappar-front/src/components/PostList.vue
  front/shappar-front/src/components/Search.vue
  front/shappar-front/src/router/index.js
  front/shappar-front/src/services/api.js
  front/shappar-front/src/views/MyPage.vue
  front/shappar-front/src/views/New.vue
  front/shappar-front/src/views/PostDetails.vue
  front/shappar-front/src/views/Public.vue
  front/shappar-front/src/views/UpdateUser.vue
  static/css/app.06907c02.css
  static/css/app.ad37c08c.css
  static/js/app.53e78066.js
  static/js/app.83cfdc30.js
  static/js/chunk-vendors.803e2619.js
  static/precache-manifest.08855e5dda7ca2324e3257998182eabb.js
  static/service-worker.js
  templates/index.html
Labels: bug, modify

#235 [add] CloudFrontの名前解決＆年齢フィールドのセレクトメニューを追加
  accounts/forms.py
  static/precache-manifest.08855e5dda7ca2324e3257998182eabb.js
  static/service-worker.js
  templates/index.html
Labels: update

#236 [deploy]本番環境へデプロイ
  accounts/forms.py
  apiv1/models.py
  apiv1/tests/test_views.py
  front/shappar-front/package-lock.json
  front/shappar-front/public/index.html
  front/shappar-front/src/assets/common.scss
  front/shappar-front/src/components/DrawerMenu.vue
  front/shappar-front/src/components/PostList.vue
  front/shappar-front/src/components/Search.vue
  front/shappar-front/src/router/index.js
  front/shappar-front/src/services/api.js
  front/shappar-front/src/views/MyPage.vue
  front/shappar-front/src/views/New.vue
  front/shappar-front/src/views/PostDetails.vue
  front/shappar-front/src/views/Public.vue
  front/shappar-front/src/views/UpdateUser.vue
  requirements.txt
  static/css/app.06907c02.css
  static/css/app.ad37c08c.css
  static/js/app.53e78066.js
  static/js/app.83cfdc30.js
  static/js/chunk-vendors.803e2619.js
  static/precache-manifest.08855e5dda7ca2324e3257998182eabb.js
  static/precache-manifest.fa5baddb5d1c12c327873772cf15fb50.js
  static/service-worker.js
  templates/index.html
Labels: deploy

#237 [mod] CloudFrontのURLを修正
  static/precache-manifest.08855e5dda7ca2324e3257998182eabb.js
  static/service-worker.js
  templates/index.html
Labels: modify

#238 [deploy]本番環境へデプロイ
  static/precache-manifest.08855e5dda7ca2324e3257998182eabb.js
  static/service-worker.js
  templates/index.html
Labels: deploy

#240 [add] 自動ユーザー作成機能を追加
  accounts/adapter.py
  accounts/admin.py
  config/create.py
Labels: update

#242 [add] 簡単ユーザー自動作成機能を追加
  accounts/custom_views.py
  accounts/forms.py
  accounts/urls.py
  config/create.py
  config/settings/local.py
  static/account/css/style.css
  templates/account/create_user.html
Labels: update

#249 [add] 投稿一覧表示機能のテストを追加しました！
  accounts/custom_views.py
  accounts/forms.py
  apiv1/tests/test_views.py
Labels: update

#252 投稿作成時のシリアライザのテストを追加！
  apiv1/serializers.py
  apiv1/tests/test_serializers.py
Labels: update

#255 [add] サインアップやログインで機能の追加&修正
  accounts/custom_views.py
  accounts/forms.py
  config/urls.py
  config/views.py
  templates/account/custom_email_confirmed.html
  templates/account/email_confirm.html
  templates/home.html
Labels: modify, update

#264 [add] 合計投票数に関するシリアライザのテストを追加
  .gitignore
  apiv1/migrations/0002_auto_20200419_0446.py
  apiv1/models.py
  apiv1/serializers.py
  apiv1/tests/test_serializers.py
Labels: update

#267 [add]フロントのテストを追加
  front/shappar-front/__mocks__/api.js
  front/shappar-front/__mocks__/localstorageMock.js
  front/shappar-front/__tests__/App.spec.js
  front/shappar-front/__tests__/components/DoughnutChart.spec.js
  front/shappar-front/__tests__/components/DrawerMemu.spec.js
  front/shappar-front/__tests__/components/GlobalMessage.spec.js
  front/shappar-front/__tests__/components/PostList.spec.js
  front/shappar-front/__tests__/components/Search.spec.js
  front/shappar-front/__tests__/components/UpdateUser.spec.js
  front/shappar-front/__tests__/views/LoginPage.spec.js
  front/shappar-front/__tests__/views/MyPage.spec.js
  front/shappar-front/__tests__/views/New.spec.js
  front/shappar-front/__tests__/views/PostDetails.spec.js
  front/shappar-front/__tests__/views/Public.spec.js
  front/shappar-front/package-lock.json
  front/shappar-front/package.json
  front/shappar-front/src/components/DrawerMenu.vue
  front/shappar-front/src/components/GlobalMessage.vue
  front/shappar-front/src/components/PostList.vue
  front/shappar-front/src/components/Search.vue
  front/shappar-front/src/services/api.js
  front/shappar-front/src/store/index.js
  front/shappar-front/src/views/Home.vue
  front/shappar-front/src/views/LoginPage.vue
  front/shappar-front/src/views/MyPage.vue
  front/shappar-front/src/views/New.vue
  front/shappar-front/src/views/PostDetails.vue
  front/shappar-front/src/views/UpdateUser.vue
Labels: enhancement
